### ISSUE TITLE
Permission to buy specific region

### ISSUE THREAD

**Issue by eduardopilati** [alex9849/advanced-region-market#129]
My regionkind: 

```
RegionKinds:
    culto:
        item: RED_BED
        displayName: Culto
        displayInLimits: true
        displayInRegionfinder: true
        lore:
        - Default lore
        displayInGUI: true
        activateRegionKindPermissions: true
```

My limit:
```
Limits:
    culto:
        total: -1
        regionkinds:
            culto: 1
```

My region:

```
      casaculto3:
          sold: true
          paybackPercentage: 0
          isHotel: false
          lastreset: 0
          lastLogin: 1667242909421
          maxMembers: -1
          regiontype: sellregion
          autoprice: culto
          signs:
          - world;4864.0;70.0;-217.0;GROUND;WEST
          kind: culto
          flagGroup: Default
          inactivityReset: true
          entityLimitGroup: Default
          autorestore: false
          allowedSubregions: 0
          userrestorable: false
          boughtExtraTotalEntitys: 0
          isprotectionofcontinuance: false
          boughtExtraEntitys: []
```

the player has permissions:

arm.member.*  true
arm.limit.* false

and still you can buy the region, is there any extra configuration for this limit to work?
